name       : python-jeepney
version    : 0.7.1
release    : 5
source     :
    - https://pypi.io/packages/source/j/jeepney/jeepney-0.7.1.tar.gz : fa9e232dfa0c498bd0b8a3a73b8d8a31978304dcef0515adc859d4e096f96f4f
homepage   : https://gitlab.com/takluyver/jeepney
license    : MIT
component  : programming.python
summary    : Pure Python DBus interface
description: |
    Low-level, pure Python DBus protocol client. It has an I/O-free core, and integration modules for different event loops.
builddeps  :
    - python-async_timeout
    - python-pytest
    - python-testpath
    - python-trio
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
