name       : python-jeepney
version    : 0.4.3
release    : 1
source     :
    - https://pypi.io/packages/source/j/jeepney/jeepney-0.4.3.tar.gz : 3479b861cc2b6407de5188695fa1a8d57e5072d7059322469b62628869b8e36e
license    : MIT
component  : programming.python
summary    : Pure Python DBus interface
description: |
    Low-level, pure Python DBus protocol client. It has an I/O-free core, and integration modules for different event loops.
builddeps  :
    - python-pytest
    - python-testpath
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
