name       : python-jeepney
version    : 0.6.0
release    : 2
source     :
    - https://pypi.io/packages/source/j/jeepney/jeepney-0.6.0.tar.gz : 7d59b6622675ca9e993a6bd38de845051d315f8b0c72cca3aef733a20b648657
license    : MIT
component  : programming.python
summary    : Pure Python DBus interface
description: |
    Low-level, pure Python DBus protocol client. It has an I/O-free core, and integration modules for different event loops.
builddeps  :
    - python-pytest
    - python-testpath
    - python-trio
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
